from django.urls import path
from .views import merhaba, hello, hakkimda, about_me, neler_yaptim, what_I_did, deneyimlerim, experiences, projelerim, projects, proje_tez, tez_en, video_tez, video_tez_en, proje_staj, staj_en, proje_staj_genis, tedas_ext, proje_staj_sunum, tedas_pre, proje_sasamakro,sasamakro_en, proje_veri, veri_en, proje_network,network_en, proje_project_planning, project_planning_en, proje_regresyon, reg_en

urlpatterns = [
    path('', merhaba, name='anasayfa'),
    path('merhaba/', merhaba, name='merhaba'),
    path('hello/', hello, name='hello'),
    path('hakkimda/', hakkimda, name='hakkimda'),
    path('about_me/', about_me, name='about_me'),  
    path('neler-yaptim/', neler_yaptim, name='neler_yaptim'),
    path('what_I_did/', what_I_did, name='what_I_did'),  
    path('deneyimlerim/', deneyimlerim, name='deneyimlerim'),
    path('experiences/', experiences, name='experiences'),
    path('projelerim/', projelerim, name='projelerim'),
    path('projects/', projects, name='projects'),
    path('projelerim/proje_tez', proje_tez, name='proje_tez'),
    path('projects/tez_en', tez_en, name='tez_en'),
    path('projelerim/proje_tez/video_tez', video_tez, name='video_tez'),
    path('projects/tez_en/video_tez_en', video_tez_en, name='video_tez_en'),
    path('projelerim/spark/', proje_staj, name='proje_staj'),
    path('projects/spark/', staj_en, name='staj_en'),
    path('projelerim/spark/tedas_genis/', proje_staj_genis, name='tedas_genis'),
    path('projects/spark/tedas_ext/', tedas_ext, name='tedas_ext'),
    path('projelerim/spark/tedas_sunum/', proje_staj_sunum, name='tedas_sunum'),
    path('projects/spark/tedas_pre/', tedas_pre, name='tedas_pre'),
    path('projelerim/sasamakro_tr', proje_sasamakro, name='proje_sasamakro'),
    path('projects/sasamakro_en', sasamakro_en, name='sasamakro_en'),
    path('projelerim/veri_bilimi_tr', proje_veri, name='proje_veri'),
    path('projects/veri_en', veri_en, name='veri_en'),    
    path('projelerim/network_tr', proje_network, name='proje_network'),
    path('projects/network_en', network_en, name='network_en'),
    path('projelerim/project_planning_tr', proje_project_planning, name='proje_project_planning'),
    path('projects/project_planning_en', project_planning_en, name='project_planning_en'),
    path('projelerim/regresyon_tr', proje_regresyon, name='proje_regresyon'),
    path('projects/reg_en', reg_en, name='reg_en'),
]
